apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafe-report
  name: kafe-report
  namespace: kafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafe-report
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafe-report
    spec:
      containers:
      - image: 839325387125.dkr.ecr.ap-northeast-2.amazonaws.com/kafe-report:latest
        name: kafe-report
        imagePullPolicy: Always
        resources: {}
        envFrom:
        - secretRef:
            name: report-env
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafe-report
  name: kafe-report
  namespace: kafe
spec:
  ports:
  - port: 48084
    protocol: TCP
    targetPort: 8080
  selector:
    app: kafe-report
  type: NodePort
status:
  loadBalancer: {}

