apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kafe-service
  name: kafe-service
  namespace: kafe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafe-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kafe-service
    spec:
      containers:
      - image: 503984144450.dkr.ecr.ap-northeast-2.amazonaws.com/kafe-service:latest
        imagePullPolicy: Always
        name: kafe-service
        resources: {}
        volumeMounts:
        - name: properties
          mountPath: /configuration
          readOnly: true
      volumes:
      - name: properties
        secret:
          secretName: service-properties
          optional: false
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafe-service
  name: kafe-service
  namespace: kafe
spec:
  ports:
  - port: 48081
    protocol: TCP
    targetPort: 8080
  selector:
    app: kafe-service
  type: NodePort
status:
  loadBalancer: {}
