apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1
  namespace: mysql-cluster
spec:
  storageClassName: gp2
  capacity: 
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-02b353a5f6114067c
