apiVersion: v1
kind: PersistentVolume
metadata:
  name: redirect-pv-0
  namespace: kafe
spec:
  storageClassName: gp2
  capacity: 
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: kafe
    name: redirect-pvc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0199e7cbe8cdcb8ed
